### ISSUE TITLE
Kanban Task Asignment

### ISSUE THREAD

**Issue by indigodavid** [indigodavid/catalog_of_my_things#21]
This is the link to our GitHub project https://github.com/indigodavid/catalog_of_my_things
Our team consists of three members:

- Oyelakin Ridwan
- Jesús Vázquez
- David Vera

## Group Tasks

- [x] Create Item class
- [ ] Create main.rb file

## Member 1 tasks: Jesús Vázquez
- [ ] Create a Book Class
- [ ] Create a Label Class
- [ ] Implement book and label options in UI.
- [ ] Add unit tests for methods in classes Book and Label.
- [ ] Preserve Book and Label in JSON files
- [ ] Append the Book and Label tables to the sql database.

## Member 2 tasks: Oyelakin Ridwan

- [ ] Create a MusicAlbum Class
- [ ] Create Genre Class
- [ ] Implement options in UI
- [ ] Add unit tests for methods in classes MusicAlbum and Genre
- [ ] Preserve MusicAlbum and Genre in JSON files
- [ ] Append the MusicAlbum and Genre tables to the sql database.

## Member 3 tasks: David Vera

- [ ] Create Game class
- [ ] Create Author class
- [ ] Implement Game and Author UI
- [ ] Add unit tests for methods in classes Game and Author
- [ ] Preserve Game and Author in JSON files
- [ ] Append the Game and Author tables to the sql database

**Comment by OLIPLICHE** [comment]
Hi TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- You did an Impressive Job. Your Kanban is excellent. All the best  👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by indigodavid** [comment]
@OLIPLICHE Thank you for your approval. We'll work on the project right now!!

Best regards and happy coding!
